services:
  app:
    build:
      context: .
    ports:
      - "8982:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: anocat_db
    hostname: anocat_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: