"""Added: First init

Revision ID: 2704d40bfac7
Revises: 
Create Date: 2025-04-06 20:37:39.410117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2704d40bfac7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('allows_write_to_pm', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mails',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_deleted_by_receiver', sa.Boolean(), nullable=False),
    sa.Column('is_deleted_by_sender', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mails_id_receiver_id', 'mails', ['id', 'receiver_id'], unique=False)
    op.create_index('ix_mails_id_sender_id', 'mails', ['id', 'sender_id'], unique=False)
    op.create_index('ix_mails_receiver_id', 'mails', ['receiver_id'], unique=False)
    op.create_index('ix_mails_sender_id', 'mails', ['sender_id'], unique=False)
    op.create_table('users__black_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users__stop_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users__stop_words_user_id', 'users__stop_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_users__stop_words_word'), 'users__stop_words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users__stop_words_word'), table_name='users__stop_words')
    op.drop_index('ix_users__stop_words_user_id', table_name='users__stop_words')
    op.drop_table('users__stop_words')
    op.drop_table('users__black_list')
    op.drop_index('ix_mails_sender_id', table_name='mails')
    op.drop_index('ix_mails_receiver_id', table_name='mails')
    op.drop_index('ix_mails_id_sender_id', table_name='mails')
    op.drop_index('ix_mails_id_receiver_id', table_name='mails')
    op.drop_table('mails')
    op.drop_table('users')
    # ### end Alembic commands ###
