"""Added: datetime mixin server default

Revision ID: c920192fbb02
Revises: 2704d40bfac7
Create Date: 2025-04-07 10:59:09.667886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c920192fbb02'
down_revision: Union[str, None] = '2704d40bfac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'created_at',
        server_default=sa.text('NOW()'),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'users',
        'updated_at',
        server_default=sa.text('NOW()'),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'mails',
        'created_at',
        server_default=sa.text('NOW()'),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'mails',
        'updated_at',
        server_default=sa.text('NOW()'),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'users__black_list',
        'created_at',
        server_default=sa.text('NOW()'),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'users__black_list',
        'updated_at',
        server_default=sa.text('NOW()'),
        existing_type=sa.DateTime(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'updated_at',
        server_default=None,
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'users',
        'created_at',
        server_default=None,
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'mails',
        'updated_at',
        server_default=None,
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'mails',
        'created_at',
        server_default=None,
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'users__black_list',
        'updated_at',
        server_default=None,
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        'users__black_list',
        'created_at',
        server_default=None,
        existing_type=sa.DateTime(),
    )
    # ### end Alembic commands ###
